server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ead_course
    username: decoder
    password: decoder
  jpa:
    hibernate:
      ddl-auto: update
#      dialect: org.hibernate.dialect.PostgreSQLDialect
#      jdbc:
#        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
